### ISSUE TITLE
Adding newsletter, and new blog post section

### ISSUE THREAD

**Issue by nyomansunima** [nyomansunima/official-site#45]
# About
Adding a new newsletter form in bio link and blog, and on main website

## Tasks

- [x] Create Newsletter on bio profile
- [x] Create newsletter on blog, and blog detail
- [x] Create newsletter on main home website
