### ISSUE TITLE
Feature: Adding Custom blog sections

### ISSUE THREAD

**Issue by nyomansunima** [nyomansunima/official-site#46]
# About
Update the blog section page using custom schema in sanity. So I can write my blog directly from sanity cms. Then showing to the blog pages

## Tasks

- [x] Define blog design and feature
- [x] Create sanity schema
- [x] Create Frontend
- [x] Publish content
- [x] Adding a feature to integrated with dev.to, hashnode and medium
