### ISSUE TITLE
Feature: Merging the current bio to my personal website

### ISSUE THREAD

**Issue by nyomansunima** [nyomansunima/official-site#47]
# About
I have a seperate website that doing this, Handle my link on profile, and other bio link. So this kinda like i need to manage different studio instead. I want to merge into a my personal website and reach the frontend at `/bio` path

## Tasks

- [x] Merging code
- [x] Moving the schema
- [x] Update the content
- [x] archive the project
